### ISSUE TITLE
EMFILE error on OS X

### ISSUE THREAD

**Issue by vjunloc** [TFaga/generator-react-reflux#12]
Getting this error on saving file.
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE, open '/Users/vijaytyagi/Documents/react_things/react_todo/node_modules/react-router/node_modules/when/lib/Promise.js'

Any help would be appreciated.

**Comment by TFaga** [comment]
Hi,

sorry for the late reply, have you figured anything on this issue? I haven't been able to reproduce it. If it's still a problem could you possibly add some additional information like generator version, options used, when the error occurs (on build, on serve, on change, ...)?

**Comment by vjunloc** [comment]
Setting up the ulimit in the terminal (ulimit -n 10480) fixed the problem, my guess is this is OS X specific. As for the details requested.
1. I am using the latest version
2. Using the default options
3. Error occurs on change.

Let me know if any other details are required.

**Comment by TFaga** [comment]
It appears that there is an issue in browserify that for when you have a lot of files in the project it starts to generate a large number of file descriptor and so hits the shell limit. It does appear to be OS X specific and the fix is the one you provided. Thanks for pointing it out.
