### ISSUE TITLE
Cant generate new app

### ISSUE THREAD

**Issue by NetanelBasal** [TFaga/generator-react-reflux#25]
i am get this error on generate new app:

```
/Users/netanelbasal/.nvm/v0.10.35/lib/node_modules/generator-react-reflux/node_modules/yeoman-generator/lib/base.js:466
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: Object #<Object> has no method 'on'
```

**Comment by pistolero77** [comment]
Hi,
You just need to update Yeoman Generator before to generate your new app, with the command below:
npm install -g yo

**Comment by NetanelBasal** [comment]
I did i am using version 1.4.5 and still get this error

**Comment by pistolero77** [comment]
My current version is 1.4.6, maybe update Yeoman again and retry...

**Comment by NetanelBasal** [comment]
Thanks it is working.
