### ISSUE TITLE
appGenerator is called instead actionsGenerator

### ISSUE THREAD

**Issue by yannickschuchmann** [TFaga/generator-react-reflux#26]
```
 $ yo react-reflux:actions api                                                                                                                    [17:27:53]

     _-----_
    |       |    .--------------------------.
    |--(o)--|    | Welcome to the excellent |
   `---------´   |  React Reflux generator! |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include ReactJS, React-Router, ReFlux, jQuery.
? What is the project's name? (api) 
```

First of all, nice work :+1: 

But it seems that both ```yo react-reflux:actions actionName``` and singular version: ```yo react-reflux:action``` trigger app generator instead of actions generator.

**Comment by TFaga** [comment]
Hi!

I just tried to run the actions generator with the latest version and it seems to work OK. Here is the output:

```bash
$ yo react-reflux:actions api
   create app/scripts/actions/ApiActions.js
```

Which version of the generator and yeoman are you using?

**Comment by yannickschuchmann** [comment]
Hey,

```generator-react-reflux@1.4.1```
```yo --version
1.4.6```
```node --version
v0.12.2
```
strange..

**Comment by pistolero77** [comment]
Hi,

It works well for me also.
The only difference I have is:
>node --version
>v0.10.29

**Comment by pistolero77** [comment]
Re,

I tested with node v0.12.2, and I have the same issue as you !
So I confirm the issue with latest node version. Need a fix.

**Comment by TFaga** [comment]
Interesting, I've upgraded my node version (it was `v0.12.0` before) and it still seems to work for me.

```bash
$ yo --version
1.4.6

$ node --version
v0.12.2

$ npm --version
2.7.5

$ yo react-reflux:actions api
   create app/scripts/actions/ApiActions.js
```

I am using OS X Yosemite 10.10.3 so maybe thats the difference. Which OS-es are you using?

**Comment by pistolero77** [comment]
Windows 7, I will try to investigate on my side. Perhaps it is a bug of Node.js for Windows...

**Comment by TFaga** [comment]
I tried it on windows and indeed it's not working. Will try to figure out whats the problem.

**Comment by yannickschuchmann** [comment]
I'm even using OS X 10.10.3.
Thanks for your effort

**Comment by pistolero77** [comment]
I tested again with the master branch code, and it works now.
Seems it occurs randomly! Very strange...

**Comment by pistolero77** [comment]
I re tested with latest release, and yo react-reflux:actions still doesn't work (see below).
The future release will fix the issue if we are lucky enough...   :-)

D:\Projets\workspaces\test>yo react-reflux:component dashboard
   create app\scripts\components\dashboard.jsx

D:\Projets\workspaces\test>yo react-reflux:store user
   create app\scripts\stores\UserStore.js

D:\Projets\workspaces\test>yo react-reflux:actions user

     _-----_
    |       |    .--------------------------.
    |--(o)--|    | Welcome to the excellent |
   `---------´   |  React Reflux generator! |
    ( _´U`_ )    '--------------------------'
    /___A___\
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I include ReactJS, React-Router, ReFlux, jQuery.
? What is the project's name? (user)

**Comment by TFaga** [comment]
Really interesting. Same thing, on the master branch it works ok.

**Comment by TFaga** [comment]
Closing for now. Issue seems to be resolved with the new version.

**Comment by gjactat** [comment]
Still got this issue with the latest versions. Fixed it by manually adding the missing "actions" folder in my AppData\Roaming\npm\node_modules\generator-react-reflux folder.
Maybe related to the package.json that mentions the following :
```javascript
  ...
  "files": [
    "app",
    "component",
    "store"
  ],
  ...
```
Shouldn't we get "actions" as well in this array ?

**Comment by TFaga** [comment]
Yes, good catch this was the issue. I was testing locally on windows using `npm link` and it worked, so I assumed everything was ok. Will update immediately.
