### ISSUE TITLE
When creating a action, It starts the new project flow

### ISSUE THREAD

**Issue by Neablis** [TFaga/generator-react-reflux#33]
Steps:
1) type  "yo react-reflux:actions user"
2) Get Welcome to the excellent
           React Reflux generator!

**Comment by evgenykochetkov** [comment]
I also encountered this yesterday, and submitted a [pr](https://github.com/TFaga/generator-react-reflux/pull/32) to fix this.
If you want to manually fix it on your machine, download/clone the repo and put "actions" folder in whatever location `generator-react-reflux` is installed.

**Comment by TFaga** [comment]
Duplicate #26. The issue was fixed and an update will be issued today.
